# Default values for test-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 3
testerPodName: tester
namespace: dev
label: testlabel
ala: alamakota
servicePort : 3030
PROTO : TCP
targetPort : 8080
obraz:
  image: gimboo/nginx_nonroot
  imagePolicy: Always


